version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 15
    target-branch: master
    reviewers:
      - nadnoslen
    labels:
      - dependencies
    ignore:
      - dependency-name: ember-cli
      - dependency-name: ember-data
      - dependency-name: ember-source
